### ISSUE TITLE
WebApiとActionMappingのアノテーションのタイプミス修正

### ISSUE THREAD

**Issue by yumaishida** [dentsusoken/iPLAss#1215]
WebApiとActionMappingのアノテーションのタイプミス修正。

- privilaged ⇒ privileged
- accessControlAllowOrign ⇒ accessControlAllowOrigin
（これはWebApiのみ）

**Comment by rikouki-isid** [comment]
_(English)_

Correct typos in WebApi and ActionMapping annotations.

Incorrect: privilaged; Correct: privileged
Incorrect: accessControlAllowOrign; Correct: accessControlAllowOrigin
(This is WebApi only)
