### ISSUE TITLE
全文検索、多重度複数のプロパティで値にnullが含まれると、クロールでエラーが発生する

### ISSUE THREAD

**Issue by xkazama-yukio3** [dentsusoken/iPLAss#1380]
全文検索、多重度複数のプロパティで値にnullが含まれると、クロールでエラーが発生する。

CSVのインポートデータや、独自の登録処理などで、プロパティに対して、
`"値1",,"値2","値3"`
のように途中にnullのデータが含まれていると、クロール時にNullPointerExceptionが発生する。

**Comment by rikouki-isid** [comment]
_English_

An error will occur during crawling in fulltext search, if the values contain null in the multiplicity multiple properties.
For properties using CSV import data or unique registration processing,
["value1",,"value2","value3"]
If null data is included in the middle, like this, a NullPointerException will occur during crawling.
