### ISSUE TITLE
EntityCRUD API、制御オプションを指定可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [dentsusoken/iPLAss#1385]
EntityCRUD API、制御オプションを指定可能にする。
インサート時のInsertOption、更新時のUpdateOption相当の制御フラグ、バルク処理有無などadminConsole相当の制御を可能にする。
adminユーザ（またEntityWebApiServiceで定義される制御オプション指定を許可するロール）でのAPI呼び出し時には、それら制御オプションを利用できるようにする。

※システム間のバックエンドでの連携時等にこの制御オプションを利用すること想定。

**Comment by yoshiharuyasuda** [comment]
_(English)_
EntityCRUD API, allows specifying control options.
Enables control equivalent to adminConsole, such as InsertOption when inserting, control flags equivalent to UpdateOption when updating, and whether or not to perform bulk processing.
When calling the API as an admin user (or a role that allows specifying control options defined in EntityWebApiService), these control options can be used.

*It is assumed that this control option will be used when linking systems at the back end.
