### ISSUE TITLE
カレンダー、データの新規登録ボタンの表示制御を追加

### ISSUE THREAD

**Issue by yoshiharuyasuda** [dentsusoken/iPLAss#1396]
カレンダーの新規登録ボタン、エンティティ毎に登録可否を設定できるようにする。
また、登録不可時や権限がない場合で、追加ができない場合は新規登録ボタンを非表示にする。

**Comment by rikouki-isid** [comment]
_English_

The add button for calendar, enable setting whether to allow entry of records for each entity.
Also, if entry of records is not possible or if you do not have permission to create a reord, the add button will be hidden.
