### ISSUE TITLE
AdminConsole、プロパティのRangeタイプのValidator設定でMin/Maxに負の数や小数を指定できない

### ISSUE THREAD

**Issue by yumaishida** [dentsusoken/iPLAss#1411]
AdminConsole、プロパティのRangeタイプのValidatorでMin/Maxに負の数や小数を指定できない。
現状、[0-9]の数字のみ入力可能になっているので修正する。

**Comment by rikouki-isid** [comment]
_English_

AdminConsole, negative numbers or decimals cannot be specified for Min/Max in the property Range type Validator.
Currently, only numbers [0-9] can be entered, so this will be corrected.
