### ISSUE TITLE
jQuery、その他のWebJars管理のJavaScriptライブラリバージョンアップ

### ISSUE THREAD

**Issue by yumaishida** [dentsusoken/iPLAss#1412]
- jQuery、その他のWebJars管理のJavaScriptライブラリバージョンアップ
- jQuery and other WebJars-managed JavaScript library version upgrades

**Comment by rikouki-isid** [comment]
gemモジュールで利用しているjqueryライブラリバージョンアップ。合わせて他のgem系ライブラリをバージョンアップ。

### Changed libraries
| library | from | to |
| --- | --- | --- |
| org.webjars:jquery | 3.5.1 | 3.7.1 |
| org.webjars.bowergithub.jquery:jquery-ui   -> org.webjars.npm:jquery-ui | 1.13.2 | 1.13.3 |
| org.webjars:pdf-js | 4.2.67 | 4.4.168 |
| org.webjars:momentjs  -> org.webjars.npm:moment | 2.29.4 | 2.30.1 |
| org.webjars.npm:viewerjs | 1.9.0 | 1.11.1 |
| org.webjars.bower:blueimp-file-upload  -> org.webjars.npm:blueimp-file-upload | 10.30.1 | 10.32.0 |
| org.webjars.bower:mediaelement  -> org.webjars.npm:mediaelement | 4.2.5 | 4.2.17 |
| org.webjars.bower:fullcalendar  -> org.webjars.npm:fullcalendar | 3.10.2 | 3.10.5 |

### Unchanged libraries
| library | current |
| --- | --- |
| org.webjars:ckeditor | 4.22.1 |
| org.webjars:jquery-blockui | 2.70-1 |
| org.webjars:jQuery-Timepicker-Addon | 1.6.3 |
| org.webjars.npm:free-jqgrid | 4.15.5 |
| org.webjars.npm:jqtree | 1.4.9 |
| org.webjars:font-awesome | 5.13.1 |

### Compatibility notes
gemモジュール内で上記ライブラリを利用したカスタムコードを記述している場合、影響がでる可能性があるので、ご確認ください。

**Comment by rikouki-isid** [comment]
_(English)_
Upgrade the jquery library used in gem module. At the same time, other gem libraries have been upgraded.

### Changed libraries
| library | from | to |
| --- | --- | --- |
| org.webjars:jquery | 3.5.1 | 3.7.1 |
| org.webjars.bowergithub.jquery:jquery-ui   -> org.webjars.npm:jquery-ui | 1.13.2 | 1.13.3 |
| org.webjars:pdf-js | 4.2.67 | 4.4.168 |
| org.webjars:momentjs  -> org.webjars.npm:moment | 2.29.4 | 2.30.1 |
| org.webjars.npm:viewerjs | 1.9.0 | 1.11.1 |
| org.webjars.bower:blueimp-file-upload  -> org.webjars.npm:blueimp-file-upload | 10.30.1 | 10.32.0 |
| org.webjars.bower:mediaelement  -> org.webjars.npm:mediaelement | 4.2.5 | 4.2.17 |
| org.webjars.bower:fullcalendar  -> org.webjars.npm:fullcalendar | 3.10.2 | 3.10.5 |

### Unchanged libraries
| library | current |
| --- | --- |
| org.webjars:ckeditor | 4.22.1 |
| org.webjars:jquery-blockui | 2.70-1 |
| org.webjars:jQuery-Timepicker-Addon | 1.6.3 |
| org.webjars.npm:free-jqgrid | 4.15.5 |
| org.webjars.npm:jqtree | 1.4.9 |
| org.webjars:font-awesome | 5.13.1 |

### Compatibility notes
If you have written custom code using the above libraries in a gem module, please check the impact may occur.
