### ISSUE TITLE
REST JSON形式のWebAPIでparameterTypeにEntityが指定されたとき、多重度複数のBinary型プロパティのマッピングがあるとエラーになる

### ISSUE THREAD

**Issue by yumaishida** [dentsusoken/iPLAss#1429]
REST JSON形式のWebAPIでparameterTypeにEntityが指定されたとき、多重度複数のBinary型プロパティのマッピングがあるとエラーになる。

**Comment by HiguchiKiyoshi** [comment]
_(English)_
In REST JSON format WebAPI, when Entity is specified in parameterType, an error occurs if there is a mapping of multiplicity multiple Binary type properties.
