### ISSUE TITLE
全文検索、バイナリパース時に想定外の例外が発生しても処理継続する

### ISSUE THREAD

**Issue by xsekiguchi** [dentsusoken/iPLAss#1459]
全文検索でバイナリパース時に想定外の例外が発生すると、インデックス構築が途中で実施できなくなってしまう。
許容する例外を指定し処理継続できるようにする。

**Comment by HiguchiKiyoshi** [comment]
_(English)_
If an unexpected exception occurs during binary parsing in full-text search, index construction cannot be performed during the process.
Specify acceptable exceptions so that processing can continue.
