### ISSUE TITLE
GEM: Select、BooleanおよびReferenceのプロパティエディタで１項目毎に改行するかどうかを設定可能にする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [dentsusoken/iPLAss#1479]
GEM: Select、BooleanおよびReferenceのプロパティエディタで１項目毎に改行するかどうかを設定可能にする

**Comment by yumaishida** [comment]
_(English)_
GEM: Enables setting whether or not a new line is inserted for each item in the Select, Boolean and Reference property editors.
