### ISSUE TITLE
GEM、ReferencePropertyEditorで「選択」や「新規」で動的に追加した参照リンクに対して入力カスタムスタイルが適用されない

### ISSUE THREAD

**Issue by yumaishida** [dentsusoken/iPLAss#1484]
GEM、ReferencePropertyEditorで「選択」や「新規」で動的に追加した参照リンクに対して入力カスタムスタイルが適用されない

**Comment by yoshiharuyasuda** [comment]
_(English)_
Input custom style is not applied to reference links dynamically added with "Select" or "New" in GEM, ReferencePropertyEditor
