### ISSUE TITLE
GEM、ReferencePropertyEditorでリンクの文字数が多い場合、文字の折り返しがされず、削除ボタンの表示位置がずれる

### ISSUE THREAD

**Issue by yoshiharuyasuda** [dentsusoken/iPLAss#1498]
backport of https://github.com/dentsusoken/iPLAss/issues/1485

**Comment by HiguchiKiyoshi** [comment]
_(English)_
In GEM and ReferencePropertyEditor, when the number of characters in a link is large, the characters in the link are not wrapped and go outside the display area.
Also, the delete button appears in an unintended position.
Add css to the li element of .list-add, wrap with overflow-wrap: break-word, and adjust the position of the delete button with overflow: auto.
