### ISSUE TITLE
GEM: SearchViewの通常検索でSelect型などでIS NULLを検索条件として指定可能にする

### ISSUE THREAD

**Issue by yumaishida** [dentsusoken/iPLAss#1520]
### 概要

- SearchViewの通常検索でSelect型などでIS NULLを検索条件として指定可能にする。
- 現状は、カスタマイズしない限り、通常検索でIS NULLを検索条件として指定することができない（詳細検索では、条件に「値が設定されていない」を選択することで、is nullの検索条件を追加することができる）。
- SearchView定義の設定ベースでIS NULLを検索条件として指定できるようにする。

### 実施事項（任意）

- プロパティエディタにIS NULLを検索条件として指定可能とするか否かのフラグを追加する
- 当該フラグがtrueの場合、IS NULLを検索条件として指定するための選択値を表示するようにする

**Comment by xnie-yabin2** [comment]
(English)
### Summary

- Enable the specification of IS NULL as a search condition in normal searches for Select-type fields in SearchView
- Currently, without customization, IS NULL cannot be specified as a search condition in normal searches (in advanced searches, you can add an IS NULL search condition by selecting the option "No Value").
- Make it possible to specify IS NULL as a search condition based on SearchView definition settings.

### Actions

- Add a flag in the property editor to specify whether IS NULL can be set as a search condition.
- If this flag is set to true, display the selection value for specifying IS NULL as a search condition.
