### ISSUE TITLE
GEM: CKEditor利用時に警告メッセージが表示されるのを抑制する

### ISSUE THREAD

**Issue by yumaishida** [dentsusoken/iPLAss#1554]
CKEditorの現行バージョンは既にEoLを迎えており、別のリッチテキストエディタへの移行などの検討が必要。
暫定対応として、CKEditorのデフォルト設定で「versionCheck: false」を指定することで警告メッセージを抑制する。

バージョンアップが難しい場合には、DetailView（LongTextPropertyEditor）の「RickText Editor Option」で、
```
{
    versionCheck: false
}
```
と設定することによって、警告メッセージを非表示にすることが可能。

**Comment by xkazama-yukio3** [comment]
_(English)_
The version of CKEditor in use is already EoL, and it is necessary to consider migrating to another rich text editor.
As a temporary measure, specify “versionCheck: false” in the default settings of CKEditor to suppress the warning message.

If version up is difficult, the warning message can be hidden by setting the following in the “RickText Editor Option” of PropertyEditor (LongTextPropertyEditor).

```
{
    versionCheck: false
}
```
