### ISSUE TITLE
jQuery、jQuery UIのバージョンアップ（3.2）

### ISSUE THREAD

**Issue by yumaishida** [dentsusoken/iPLAss#1636]
GEMモジュールで利用しているjQuery、jQuery UIのライブラリバージョンアップ。

### Changed libraries
| library | from | to |
| --- | --- | --- |
| org.webjars:jquery | 3.5.1 | 3.7.1 |
| org.webjars.bowergithub.jquery:jquery-ui   -> org.webjars.npm:jquery-ui | 1.13.2 | 1.13.3 |

**Comment by xnie-yabin2** [comment]
_(English)_
Version upgrade of the jQuery and jQuery UI libraries used in the GEM module.

### Changed libraries
| library | from | to |
| --- | --- | --- |
| org.webjars:jquery | 3.5.1 | 3.7.1 |
| org.webjars.bowergithub.jquery:jquery-ui   -> org.webjars.npm:jquery-ui | 1.13.2 | 1.13.3 |
